export const SHEET_NAMES = {
  USERS: "Người dùng",
  PLANS: "Lịch công tác tuần",
  ITEMS: "Chi tiết lịch công tác",
  LOGS: "Nhật ký nhắc lịch",
  CONFIG: "Cấu hình",
};

export const HEADERS = {
  [SHEET_NAMES.USERS]: [
    "Mã người dùng",
    "Mã Zalo",
    "Họ tên",
    "Ảnh đại diện",
    "Cho phép nhận nhắc lịch",
    "Đã tạo lối tắt màn hình chính",
    "Ngày tạo",
    "Cập nhật lần cuối",
  ],
  [SHEET_NAMES.PLANS]: [
    "Mã lịch tuần",
    "Mã người dùng",
    "Tuần thứ",
    "Từ ngày",
    "Đến ngày",
    "Tiêu đề lịch",
    "Ghi chú",
    "Ngày tạo",
    "Cập nhật lần cuối",
  ],
  [SHEET_NAMES.ITEMS]: [
    "Mã chi tiết",
    "Mã lịch tuần",
    "Ngày công tác",
    "Buổi",
    "Giờ bắt đầu",
    "Giờ kết thúc",
    "Nội dung công tác",
    "Địa điểm",
    "Người phối hợp",
    "Bật nhắc lịch",
    "Thời điểm đã nhắc",
    "Trạng thái",
  ],
  [SHEET_NAMES.LOGS]: [
    "Mã nhật ký",
    "Mã người dùng",
    "Mã chi tiết",
    "Loại nhắc",
    "Nội dung nhắc",
    "Thời điểm gửi",
    "Kết quả gửi",
    "Ghi chú",
  ],
};
